name: 'Deploy to FTP'
author: 'Martin Kukolos'
description: 'Containerized environment to deploy static sites to the FTP sterver'
branding:
  icon: 'package'
  color: 'black'
inputs:
  ftp-server:
    description: "Address of your FTP server"
    required: true
  ftp-user:
    description: 'User with access to your FTP share'
    required: true
  ftp-password:
    description: 'Your FTP password'
    required: false
    default: '1024M'
  source-folder:
    description: 'Folder where are files you want upload to the server'
    default: './public/'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.ftp-server }} #1
    - ${{ inputs.ftp-user }} #2
    - ${{ inputs.ftp-password }} #3
    - ${{ inputs.source-folder }} #4
